version: "2"
services:
   rabbit:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
      - TCP_PORTS=15672, 5672
    networks:
      - back
    image: gsantomaggio/rabbitmq-autocluster
    expose:
      - 15672
      - 5672
      - 5671
      - 15671
    tty: true
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server;" 
   lb:
    image: dockercloud/haproxy
    environment:
      - MODE=tcp
    links:
      - rabbit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - back
   consul1:
    image: "consul"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - back
      
volumes:
  rabbit1:
    driver: local

networks:
  back:
