# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


BOX_IMAGE = "opensuse/openSUSE-15.0-x86_64"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "node0"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
 end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      subconfig.vm.network "forwarded_port", guest: 15672, host: "#{i + 1}5762"
      subconfig.vm.network "forwarded_port", guest: 5672, host:"#{i + 5}762"
    end
  end

  # Install avahi on all machines  
  config.vm.provision "shell", inline: <<-SHELL
     sudo echo "10.0.0.11 node1 " >> /etc/hosts 
     sudo echo "10.0.0.12 node2 " >> /etc/hosts 
     sudo echo "10.0.0.10 node0 " >> /etc/hosts 
     sudo zypper addrepo  http://download.opensuse.org/repositories/devel:/languages:/erlang:/Factory/openSUSE_Leap_15.0/ el
     sudo zypper --gpg-auto-import-keys refresh
     sudo zypper -n install erlang-21.1.2-lp150.2.1
     wget  https://dl.bintray.com/rabbitmq/rpm-prereleases/rabbitmq-server/v3.8.x/opensuse/42.1/noarch/rabbitmq-server-3.8.0~beta.1-1.suse.noarch.rpm
     wget https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
     sudo rpm --import rabbitmq-release-signing-key.asc
     sudo zypper -n in rabbitmq-server-3.8.0~beta.1-1.suse.noarch.rpm
     sudo systemctl start rabbitmq-server
     sudo chmod 600   /var/lib/rabbitmq/.erlang.cookie
     sudo echo "MYCOOKIE" > /var/lib/rabbitmq/.erlang.cookie
     sudo bash -c  'echo "vm_memory_high_watermark.relative = 0.9" > /etc/rabbitmq/rabbitmq.conf'
     sudo bash -c  'echo "cluster_partition_handling = pause_minority" >> /etc/rabbitmq/rabbitmq.conf'
     sudo systemctl restart rabbitmq-server
     sudo systemctl enable rabbitmq-server
     sudo rabbitmq-plugins enable rabbitmq_management
     sudo rabbitmqctl stop_app
     sudo rabbitmqctl reset
     sudo rabbitmqctl join_cluster rabbit@node0
     sudo rabbitmqctl start_app	
     sudo rabbitmqctl add_user test test
     sudo rabbitmqctl set_user_tags test administrator
     sudo rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
     SHELL
end



